from flask import Flask,request,render_template,url_for,redirect
import database
import sys

app = Flask(__name__)
domain = "http://127.0.0.1:8080/"

@app.route("/",methods=["GET"])
def home():
    return render_template("home.html",short_url = "",long_url="",text="")

@app.route("/api/v1/data/shorten",methods=["GET","POST"])
def gen_short_url():
    if request.method=="GET":
        return redirect(url_for("home"))
    
    
    long_url = request.form['url_link']
    print("Customer entered long_url is %s"%(long_url))
    try:
        check_short_url = database.get_records(long_url=long_url)
    except Exception as e:
        print("Failed to check short_url for entered long_url with error %s" %(str(e)))
        return render_template("home.html",short_url="",long_url=long_url,text="Internal Server Error. Please retry again after sometime.")
    if check_short_url:
        return render_template("home.html",short_url=domain+check_short_url[0][0],long_url=long_url,text="")
    try:
        short_url = database.add_record(long_url)
    except Exception as e:
        print("Failed to generate short_url for long_url %s with error %s" %(long_url,str(e)))
        return render_template("home.html",short_url="",long_url=long_url,text="Internal Server Error. Please retry again after sometime.")
    
    return render_template("home.html",short_url=domain+short_url,long_url=long_url,text="")

@app.route("/<shorturl>")
def return_long_url(shorturl):
    try:
        long_url = database.get_records(short_url=shorturl)
    except Exception as e:
        print("Failed to get short_url for long_url %s with error %s" %(long_url,str(e)))
        return render_template("home.html",short_url="",long_url=long_url,text="Internal Server Error. Please retry again after sometime.")
    if not long_url:
        return render_template("home.html",short_url="",long_url="",text="Please check the url, it is not a valid short url generated by us.")
    full_url = long_url[0][0]
    return redirect(full_url, code=302)

if __name__=="__main__":
    try:
        database.create_db()
    except Exception as e:
        print("failed to intialize database.")
        sys.exit(0)
    app.run(debug=True,host="0.0.0.0",port=8080)
